[work]
source        = imaps://mail%40wantguns.dev:%23ishBr0wni3noice@imap.migadu.com
outgoing      = smtps://mail%40wantguns.dev:%23ishBr0wni3noice@smtp.migadu.com
default       = INBOX
from          = "Gunwant Jain" <mail@wantguns.dev>
cache-headers = true
copy-to       = Sent
