# ABOUT: TMUX Config
# Author: Gunwant Jain <mail@wantguns.dev>

# 0 is too far on the keeb
set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Enable true colors in tmux
set -g default-terminal "xterm-ghostty"
set -ag terminal-overrides ",xterm-ghostty:Tc"

set -g status-keys vi
set -g history-limit 1000000

setw -g mode-keys vi
setw -g mouse on
setw -g monitor-activity on
set -g set-clipboard on
set -g allow-passthrough on

set -g extended-keys on
set -g extended-keys-format csi-u

bind-key c new-window -c "#{pane_current_path}"
bind-key C new-window -a -c "#{pane_current_path}"
set -g renumber-windows on
bind-key _ split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind-key q killw

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Enter selection mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf

# Styling
set -g window-style 'bg=default'
set -g window-active-style 'bg=default'

set -g window-status-style 'fg=colour2,bg=default'
set -g window-status-current-style 'fg=colour0,bg=colour2'
set -g window-status-activity-style 'fg=colour2,bg=default,bold'
set -g window-status-bell-style 'fg=colour2,bg=default,bold'
set -g window-status-format ' #I:#W#{s/[*#]//:window_flags} '
set -g window-status-current-format ' #I:#W#{s/[*#]//:window_flags} '

set -g pane-border-style 'fg=colour2,bg=default'
set -g pane-active-border-style 'fg=colour2,bg=default'

set -g status-style 'bg=default fg=colour2'

set -g status-left-length 40

set -g status-right-length 50
set -g status-right "@CONTINUUM_SAVE@%H:%M %d-%b-%y #[fg=colour2][#(uptime | sed -E 's/.*load averages?: //; s/,/ /g; s/  +/ /g')]"
