[work]
source            = imaps://mail%40wantguns.dev@imap.migadu.com
source-cred-cmd   = ([[ "$OSTYPE" == "linux"* ]] && cat $XDG_RUNTIME_DIR/email/mail@wantguns.dev/source) || ([[ "$OSTYPE" == "darwin"* ]] && cat $(getconf DARWIN_USER_TEMP_DIR)email/mail@wantguns.dev/source)
outgoing          = smtps://mail%40wantguns.dev@smtp.migadu.com
outgoing-cred-cmd = ([[ "$OSTYPE" == "linux"* ]] && cat $XDG_RUNTIME_DIR/email/mail@wantguns.dev/outgoing) || ([[ "$OSTYPE" == "darwin"* ]] && cat $(getconf DARWIN_USER_TEMP_DIR)email/mail@wantguns.dev/outgoing)
default           = INBOX
from              = "Gunwant Jain" <mail@wantguns.dev>
cache-headers     = true
copy-to           = Sent

[void]
source            = imaps://void%40wantguns.dev@imap.migadu.com
source-cred-cmd   = ([[ "$OSTYPE" == "linux"* ]] && cat $XDG_RUNTIME_DIR/email/void@wantguns.dev/source) || ([[ "$OSTYPE" == "darwin"* ]] && cat $(getconf DARWIN_USER_TEMP_DIR)email/void@wantguns.dev/source)
outgoing          = smtps://void%40wantguns.dev@smtp.migadu.com
outgoing-cred-cmd = ([[ "$OSTYPE" == "linux"* ]] && cat $XDG_RUNTIME_DIR/email/void@wantguns.dev/source) || ([[ "$OSTYPE" == "darwin"* ]] && cat $(getconf DARWIN_USER_TEMP_DIR)email/void@wantguns.dev/source)
default           = INBOX
from              = "Gunwant Jain" <void@wantguns.dev>
cache-headers     = true
copy-to           = Sent
