apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alnitak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  description: "alnitak kubernetes cluster"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
