wg:
    mintaka:
        private: ENC[AES256_GCM,data:2Jo2LcfmFY3Eiz1Mb99cdRSPPc3/TixT7AkphLdbgmIWm6yXzpHfVqBTPFQ=,iv:C7bKZF5T8MRuzE9eMuoTDE6F25vmVPoV9qSV3BljjMY=,tag:bYMBnixmUlueZBadK/2JVQ==,type:str]
    bellatrix:
        private: ENC[AES256_GCM,data:Pu3cDh4FkM9/fp6rQxjQMU1TXt3Q8uB9st9pDFhIF8VM28gYmcjS2aL65t4=,iv:aFdRYWUjKwGO3EqkYKQM/Hk9dcYtn+MRYfsq2kNqcT8=,tag:nS+ghIkzsoutS92Vrm5icg==,type:str]
    alnitak:
        private: ENC[AES256_GCM,data:P6yOBwgJ/vzi14FC7TZo5YtzfrPL3XP8VAF3RrxBTHXDqeO6Vl4omD9H98A=,iv:r0NJRSx99UmsW0RoozEP9NjyHU4NozsfUNHrxIlaGUc=,tag:tiMBci2Q8jjme1DNn1ou5w==,type:str]
    shiba:
        private: ENC[AES256_GCM,data:wdGMV4LnAgKMq4AH7rvve5xiASWYUadEwOIpIcWGNgrIsifKuCOapb/q5qU=,iv:kmy+PhAPQ04veIuAPuL/KrTBzaoSRY+FmVO0Tg5vMKc=,tag:inpH57qPVP5WlHzagpEVOA==,type:str]
    meissa:
        private: ENC[AES256_GCM,data:O3wNDueRDguRyIvpw3mWCrm7gLfm74TN84A9DYSTZDfqa3c42/8WL+B67Jc=,iv:hYQq4kYZkDZfKjuQglYsP1cMiSBRBblF1DAjuFG+DvQ=,tag:2J/n38E2FQci8vAEE5S4Ag==,type:str]
    pyco:
        private: ENC[AES256_GCM,data:DjLsegVY2urYQ8o1cjRjywFHxbALpEVc/KF+9kC0MXBQqcvOqA31m0BZViQ=,iv:2UaZ3wSJHxzvwfuZeZhTXKq7O+FvOucTMEtEQWxcv5g=,tag:lWTKhUt4aEUiTrHkDKUePw==,type:str]
    ps:
        private: ENC[AES256_GCM,data:bASktxANDjA0MqzxKl2+uUrrikWOrAPMfPKX0zueJFrGZISQ3DWfgniQ9zM=,iv:XX6VrWWNTIlhm/H89PdFov1S80X3X+h5IQUaIN1SI2E=,tag:m/TB1BG9rrxuOwMkcNoJ6Q==,type:str]
    kps:
        private: ENC[AES256_GCM,data:G1MsszSygKzFDPhU/3WcH20eo3uacGLuPNZaP5c9vAI8d1sOozUvLCpEPQw=,iv:3xSlq3Hg8DK0PrlnyBOT96zZnWdq2KI5keAvrQIQCrI=,tag:2DHwrFzT1acS3c6XQnfwEQ==,type:str]
    wantguns-bindos:
        private: ENC[AES256_GCM,data:kYhOyDSH+1AIoDdmbfVfAQ7jgmni5Wwl4vmgTy08htj7gWD6ME2WOSnj2MI=,iv:gUUf1gZlkGhC5dPur8j9oEYuECYHra0ZP9wWya/0Neg=,tag:25OvOLrLdLHhlUrwmu06rA==,type:str]
    lota:
        private: ENC[AES256_GCM,data:qCRuywAFlOmjIKuSSvDSZKcBaSvSa62iUpJb/xlJp1tYYCghP8xWdQYSqik=,iv:1/paaP/gv7Rsub54rmUYajpseaThVBU6MXIRionG7AA=,tag:dFmd1d+JaIZtxt95IyJmxw==,type:str]
    rigel:
        private: ENC[AES256_GCM,data:/XcDNmsZx/HiBSXe11Y2UHuegY5QM7fiw6WOWNPWGCq51gYecK1zhPaxRIM=,iv:Vw358y27jxTUZFDIBlRb9R9W3mq4Do2EWuK8fZ5uL1s=,tag:VyVf86GIZjjhZ5La37xKgw==,type:str]
zfs:
    alnitak-mediapool-shared-encrypted: ENC[AES256_GCM,data:biqe+mVi5oPPPptPm7p6tKy8Q3fn19LDIQWVZ9f3PremKfoXv+RnPVeBpbTHwFIJzAtWaukLw/DMdX3Y5px/Ig==,iv:zAliat+6WCfEmA+kWvVxH1xM/bzLwNXBu4NdFguJ5HE=,tag:pezA/svUbEZHM0M1kipnYg==,type:str]
k3s:
    server_token: ENC[AES256_GCM,data:BVw/eoRF0A13Yx5ayGPzsKi58eCWLsSzAXfF2/wru97w0lr5fv0Xb1KfLyJm0t4vl9K4xiLbEQkzxlYLjJ3PTXnIZhZEO+leJ4bfZbTNTg3ET597Z0RfpQnAAqbOQsUJhuxYS1tjNQbS+YGS,iv:aZEazaUVGsgdR1KylptnTP7QLsrYYpyh0qn8CThR25I=,tag:FnYJQGzRcpLSMLz3CuWdgA==,type:str]
    agent_token: ENC[AES256_GCM,data:kPLOeWMshrY+TfsJ1wgajjmMJqrLw63vRCYNFu4t2T8ECwTAwNj/8ZE0EDNj4xaNs3jvnnOnXxajA0W0Hy9IP7GclyZ4OhvajK78UTVxNZN6IPBXHid9veNIxjOwyegb5f5qtx/oaLfoQCPj,iv:MFPdZkilXZKu+ia0MRfTX4xjjHoMuXV8XNDAoJHCOEc=,tag:Z0YFgi+wzhR7CfHUb1+YLQ==,type:str]
xray:
    alnitak: ENC[AES256_GCM,data:EnWjH2Bki6HooHHKPMt/ld8w5QJjDsaL4ecGMT2T7vmt1Q1rAmTy0a+4FngU+KKzDEkIkb+0HgbHdDbRI85NndRqP1Ls4qxCwO/SYNEYCGGLDtMUccQj7OdmV14xqpyT56xKV/8j7YJ4MJ1O//AadtCJ1zv86UM9q2w5xzVzr+7XAkYJsuSpLOaEgLY/pIfPuZVPCxHDGrVxj93NCYsvzNKOQ/bhFZTAbvalp8hiqbLAhQ/aroGGK8zJh9GiG5YH+zwKHkMupZ3O5A4q0bKiAUhlDt0U5XcFOWJGCO7EdxLBC/kVnBmPMQa6FMfZ47g5iz09X/79fDvr2N0L0r/fzpqCRcmc4Rjp50dV3yPUh+mGv2VL3UIV4pqAWFYc3ybpHcCZH2pxpWOKn8ftcxB+NStoAaNNm5l3qDArCGe6PbN1n5m4O+3Hss47FvAxI7phTPiNtHzYzQc0sJr/6HGAP3PAEwzm/iCPUM0M1NdgFRqju4O/Z6JTHA/vnldIfFjg+fiSPbVHonf9g1iZDRertwQqd8syu8+PdDChc+jYtNbIAzgNPXSixs+yxymJ6AAlDJZPlyA8QNPcHFPHKX6BMGml2c8wdpvBi9n3mVNoXbCl1v1C8m3OJ5fDRcATCOW6ulprB3Kqzn07C/zlAHxIi9OoM/Q/2wAj96Sf3VODu6EQOz62+8YoNcBl9ox8DiUae6VTNKIN4BEWaFA8/t74vr4YHWI0kVazKyd1+F1i/3s+zzHcJ40DdiQFtZFHUa3pQASF5wIymKvK8AlqoIeUrfC6V1sSofeDli+5MspxWFmqrf/JHSWNYfNsEBxLnL6LO6OEV9cb21erO6HrrqLs44SmQk6bOiIi5vDOzEFM5L3SkJD+DHEPgE0D4Ostt86471zzDQin1qQc2QxVeZq9aXjePU95EOU/XTR/fVl77GkP8fDJmLI6d1o3q8gCKgXkxfbKoDQ+E2OZuPhVu/Icam6OfFzFsztESxc8SQo8UHYRwYbc9FPt7O0XuquTJaUdcxKlLB6uG8kFXZ8jGimUvPdnGfdK1jZBTen6ENzEKFIjyyOtG/vbV4aiNj+DwR3Y7arokbnwlZmhXmPzHuuw9jwyl10+lAyBgI3YS65uXTLBpcjunP3vulL1XM2cDPdNeuWO86AtYUhYxvu9Mw3iALgWU760lVdGep23VUK7ASahMlMw50a9udAKcXcJ3MNFqxOc2ku3jxvNJbRdNyEn1hen/E4ESqyWzPyU/zt9ozfio7JbipOnnBPpitYBqWI8Yg3mGSXfXIe+w+DBLDIun3uhqL4V/AMUtjy6TUA=,iv:qdr6VIP949of3kdRzU/+KkP4wdxwsEl8VQmaIpJVUc0=,tag:petIStpCZ5WDVVy+9Xvzlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU0ZFNFhzWkRtSGw5VXBK
            eFJ5NlpWbUVGaTY2eTZzb3N3U1E0STBtWlFNCkx2VWU3STY5ckp6dFlJOTFkaGZr
            eEtudGFCWlFVMFRIU0djZEI5MGt3R3MKLS0tIDFqMjFQYzdzeUpyYnZLWmUxMVo5
            RkY4VXZKM2tlUEdXMkVtMHdKTGpSSGMKPwiq6VCtHHoEEWTApXbyb62d/BIZUDAO
            ePux3io0xl0vwcF/DcJpuTXbwGHsZ+hygLcn4KjDj6Ovbqqq2OHSpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwdptp2f9jqzugvkvapf4ssqdt3xm0mn8tq9f9xrqdf8kazsn3js6ftmg6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeUo0SG5qR3VOY3FVS2g0
            dWFoTUdDRktpdkxRQUkvWXBISTlJbktsK1g0ClA1eVUrbk1XOTN5RjliTXpsSFFr
            RkdjQWNHbGh3ZzBFZkhaUXpYcmxhTzgKLS0tIFNXVTJ0SlJBZmpHa0RMY2JyUThB
            SUkzejIySXNFU29Bb2ZsNDlVYytZS0kKsrddf9P2+p60paUMV+ASLiITFsG7ffao
            pW+1dChO6wNVPVlUL8uw+bt2KD8WaWlSvrklkAzvZivFyIxVVRrvxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwmwwqm7tm7msj9jl5yj6gxrjnkpc8qykgpux9u7x6nhg8llus4qk2e7ds
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINEhWYUhnMG5ydHdCVDl3
            K1pWdnNLdmpvbk5DdWVRNmR1UVVKTDk5VUNjCkw4YVoySWd6TTI0dnNDeW9yQUMx
            dUxTN1pWb1dPSXRtRDNzVUowcU9UQlEKLS0tIGFhTGNiL1BYaERYQkw1U1l2NmNq
            djV4VFY5Z0c5UERVczExdk5aRU0rOFUKoBfO72OSga5wLwTmJ9y1wvUhTIzrLx9W
            OnEc1cfjoA7VBxyHqC8wTQlHiAHpw4Wv2PZ+gzpU5cRviChSU2EnMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e0slax42xt6r7nzwv7kxnkshuewwefu4049zr7wswxzdelajxguqsclvt6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS3ZtNXNvc2NUTGpOMEF0
            eTN0cUM1MFpDaHFVTzgrK3Vqb2VkK29yNDNrCm1FMTJjdzdVdkNjcEZieTI1UnVE
            eGtETVRja3prbUtPaklCQzNOSTZYbVkKLS0tIHJkdjNOaFdHcHcyU01wdmgxWWZW
            OWxleFZmWDdaeDhteVNrMzdFOEE4eVkKs3oSzOsoUUyIdeEeOXTVQNt53BJTzTNh
            fFNPzctX8yoq6b8D+SCNmMc1wN4J8pQ0BlFfzYXeMocEK3DTrlg9qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cfcja4l7ar2t4cuscs4xqax22ded73re3wjcvq8ymg39jk8jmgjqnms563
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb1g1Q081UUhma1l4T09z
            MlFLTGpVK0drVjgxUXdQVTNFWE16QjRsQVd3Ck9LMjByRi8xQURIeHJOalRzQzU0
            L1FiMXVIL3dRcDBVUGlkUGJtemVZNWsKLS0tIE43WlBES25ybWE4V3ZvcHg3VVF4
            TzFYWGlFU3pYVmV4Mm1pTHNxSmEraWMKGlui4+RTK2dA+jIqqq7qY42FGkAhniJp
            DP6seVeJjXAB9csE6S+zgjdnMga8zj4+NIHzABTc5yoEDMnPt1iyMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyrdtt37tgdd7zvrhyhzptjumurdaqymv8e08nvm704u8hd8qcyqp6a3uw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWJ3SFBRK04rcDQvOWFM
            SENKOWhUQURZanJxRDVCNTBnemtFOWR2WlY0Cm5FelY2UlRON2VTc3REblhCQXZF
            MEFvalNiQkxNYkEzbmdOTzlVVCswREUKLS0tIEc5YWZYeVJwNmRNZkNTWHNJUzVl
            UURzcTF1WWZUbkY1TVVPUi9ERXhTSncKhmgtvJt3ru4a5+ale14R382rUsmsQqm5
            7HduXV+UJP0E/MhvDHEZfDCaJQuZdtxmj05BB2b24mz2tfJBIma4nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qlq2enxnf3pgn7ffnp6gc090dymrdfmahh38pu7nxnd9w0dac5ys06rh96
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QWxObXdsb3JvM0d3SkFs
            T2pwTmNhMTZpYkpab08rdGlGdE5BQjNOb1d3CnROak5kcTBhTncwRzRNVU1ScGMv
            ZTB6WC9WVzBwTVg3cHo4RmFBVXo3NmsKLS0tIHRyemNVekZxWnI4Q2VOVlgrOE9k
            ZnYwdmVNQkNKcnNGNm5sWXFGUzVFc2sKm2DD/1Q4kfc9lOG4INhGT945CiKLblD3
            BpZ8WfehpX8NCxG75PVuwE5ie7kzCvee2ORne3FL9KvppdOsM+5VCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vs330ap47fuywf4vnl6ngr5xtju06n47n06fv8pc6frpm53e895sl596tj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT05GQk94d0RBVXovdVhJ
            WnF4a0ZkZmg3Y0VveVBuWlNPZEkzbEkxc0NJCjBtbC9Wa3RBaVBpSDFFUDBab3ha
            LzBHa29tM1pPUm9SWG5mOUdtQWZvS1EKLS0tIEFUWFRRUlI1VzRzQzhSak1uR2ZD
            TXBSdnRPUWZjRDJGYmtqV1E0cW4xSW8KnTntCBvQltmCAdjEcl/Cz4TbYJz6gxBs
            cn2adiMnnfT15LErussWX2oxVV0ZTKy6nL8tYft26CcLpNtCdhq6EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gq8g3032g9r6u0c5krvdm8r3n6u4ktc3wea7xlsl7l7c378nwp2sq6x90j
    lastmodified: "2026-06-16T17:54:23Z"
    mac: ENC[AES256_GCM,data:PpX1B4QZUDDvfDnE4Jm3R1Pp3NgBcJzE6X2YWvf9pXlwa8neNB8ScpphaQyW+p08iKctQ66S5iPRv1p6r3xIYMw5lw0Vq0mdCcEYGVU5b9FApbweDEsfmPWIIyMJUqebuU/BXR5lf9iU1GpcO4Y2mLqJ8PMiqnmdTG2XteQmYhM=,iv:qvTBBma7ZXepgEUtHkUMySVVuuGoASnfT1kcXcDX+7A=,tag:rBhUVZxqfwvXDP7HMyxW+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
