wg:
    mintaka:
        private: ENC[AES256_GCM,data:2Jo2LcfmFY3Eiz1Mb99cdRSPPc3/TixT7AkphLdbgmIWm6yXzpHfVqBTPFQ=,iv:C7bKZF5T8MRuzE9eMuoTDE6F25vmVPoV9qSV3BljjMY=,tag:bYMBnixmUlueZBadK/2JVQ==,type:str]
    bellatrix:
        private: ENC[AES256_GCM,data:Pu3cDh4FkM9/fp6rQxjQMU1TXt3Q8uB9st9pDFhIF8VM28gYmcjS2aL65t4=,iv:aFdRYWUjKwGO3EqkYKQM/Hk9dcYtn+MRYfsq2kNqcT8=,tag:nS+ghIkzsoutS92Vrm5icg==,type:str]
    alnitak:
        private: ENC[AES256_GCM,data:P6yOBwgJ/vzi14FC7TZo5YtzfrPL3XP8VAF3RrxBTHXDqeO6Vl4omD9H98A=,iv:r0NJRSx99UmsW0RoozEP9NjyHU4NozsfUNHrxIlaGUc=,tag:tiMBci2Q8jjme1DNn1ou5w==,type:str]
    shiba:
        private: ENC[AES256_GCM,data:wdGMV4LnAgKMq4AH7rvve5xiASWYUadEwOIpIcWGNgrIsifKuCOapb/q5qU=,iv:kmy+PhAPQ04veIuAPuL/KrTBzaoSRY+FmVO0Tg5vMKc=,tag:inpH57qPVP5WlHzagpEVOA==,type:str]
    meissa:
        private: ENC[AES256_GCM,data:O3wNDueRDguRyIvpw3mWCrm7gLfm74TN84A9DYSTZDfqa3c42/8WL+B67Jc=,iv:hYQq4kYZkDZfKjuQglYsP1cMiSBRBblF1DAjuFG+DvQ=,tag:2J/n38E2FQci8vAEE5S4Ag==,type:str]
    pyco:
        private: ENC[AES256_GCM,data:DjLsegVY2urYQ8o1cjRjywFHxbALpEVc/KF+9kC0MXBQqcvOqA31m0BZViQ=,iv:2UaZ3wSJHxzvwfuZeZhTXKq7O+FvOucTMEtEQWxcv5g=,tag:lWTKhUt4aEUiTrHkDKUePw==,type:str]
    ps:
        private: ENC[AES256_GCM,data:bASktxANDjA0MqzxKl2+uUrrikWOrAPMfPKX0zueJFrGZISQ3DWfgniQ9zM=,iv:XX6VrWWNTIlhm/H89PdFov1S80X3X+h5IQUaIN1SI2E=,tag:m/TB1BG9rrxuOwMkcNoJ6Q==,type:str]
    kps:
        private: ENC[AES256_GCM,data:G1MsszSygKzFDPhU/3WcH20eo3uacGLuPNZaP5c9vAI8d1sOozUvLCpEPQw=,iv:3xSlq3Hg8DK0PrlnyBOT96zZnWdq2KI5keAvrQIQCrI=,tag:2DHwrFzT1acS3c6XQnfwEQ==,type:str]
    wantguns-bindos:
        private: ENC[AES256_GCM,data:kYhOyDSH+1AIoDdmbfVfAQ7jgmni5Wwl4vmgTy08htj7gWD6ME2WOSnj2MI=,iv:gUUf1gZlkGhC5dPur8j9oEYuECYHra0ZP9wWya/0Neg=,tag:25OvOLrLdLHhlUrwmu06rA==,type:str]
    lota:
        private: ENC[AES256_GCM,data:qCRuywAFlOmjIKuSSvDSZKcBaSvSa62iUpJb/xlJp1tYYCghP8xWdQYSqik=,iv:1/paaP/gv7Rsub54rmUYajpseaThVBU6MXIRionG7AA=,tag:dFmd1d+JaIZtxt95IyJmxw==,type:str]
    rigel:
        private: ENC[AES256_GCM,data:/XcDNmsZx/HiBSXe11Y2UHuegY5QM7fiw6WOWNPWGCq51gYecK1zhPaxRIM=,iv:Vw358y27jxTUZFDIBlRb9R9W3mq4Do2EWuK8fZ5uL1s=,tag:VyVf86GIZjjhZ5La37xKgw==,type:str]
zfs:
    alnitak-mediapool-shared-encrypted: ENC[AES256_GCM,data:biqe+mVi5oPPPptPm7p6tKy8Q3fn19LDIQWVZ9f3PremKfoXv+RnPVeBpbTHwFIJzAtWaukLw/DMdX3Y5px/Ig==,iv:zAliat+6WCfEmA+kWvVxH1xM/bzLwNXBu4NdFguJ5HE=,tag:pezA/svUbEZHM0M1kipnYg==,type:str]
k3s:
    server_token: ENC[AES256_GCM,data:BVw/eoRF0A13Yx5ayGPzsKi58eCWLsSzAXfF2/wru97w0lr5fv0Xb1KfLyJm0t4vl9K4xiLbEQkzxlYLjJ3PTXnIZhZEO+leJ4bfZbTNTg3ET597Z0RfpQnAAqbOQsUJhuxYS1tjNQbS+YGS,iv:aZEazaUVGsgdR1KylptnTP7QLsrYYpyh0qn8CThR25I=,tag:FnYJQGzRcpLSMLz3CuWdgA==,type:str]
    agent_token: ENC[AES256_GCM,data:kPLOeWMshrY+TfsJ1wgajjmMJqrLw63vRCYNFu4t2T8ECwTAwNj/8ZE0EDNj4xaNs3jvnnOnXxajA0W0Hy9IP7GclyZ4OhvajK78UTVxNZN6IPBXHid9veNIxjOwyegb5f5qtx/oaLfoQCPj,iv:MFPdZkilXZKu+ia0MRfTX4xjjHoMuXV8XNDAoJHCOEc=,tag:Z0YFgi+wzhR7CfHUb1+YLQ==,type:str]
xray:
    alnitak: ENC[AES256_GCM,data:EnWjH2Bki6HooHHKPMt/ld8w5QJjDsaL4ecGMT2T7vmt1Q1rAmTy0a+4FngU+KKzDEkIkb+0HgbHdDbRI85NndRqP1Ls4qxCwO/SYNEYCGGLDtMUccQj7OdmV14xqpyT56xKV/8j7YJ4MJ1O//AadtCJ1zv86UM9q2w5xzVzr+7XAkYJsuSpLOaEgLY/pIfPuZVPCxHDGrVxj93NCYsvzNKOQ/bhFZTAbvalp8hiqbLAhQ/aroGGK8zJh9GiG5YH+zwKHkMupZ3O5A4q0bKiAUhlDt0U5XcFOWJGCO7EdxLBC/kVnBmPMQa6FMfZ47g5iz09X/79fDvr2N0L0r/fzpqCRcmc4Rjp50dV3yPUh+mGv2VL3UIV4pqAWFYc3ybpHcCZH2pxpWOKn8ftcxB+NStoAaNNm5l3qDArCGe6PbN1n5m4O+3Hss47FvAxI7phTPiNtHzYzQc0sJr/6HGAP3PAEwzm/iCPUM0M1NdgFRqju4O/Z6JTHA/vnldIfFjg+fiSPbVHonf9g1iZDRertwQqd8syu8+PdDChc+jYtNbIAzgNPXSixs+yxymJ6AAlDJZPlyA8QNPcHFPHKX6BMGml2c8wdpvBi9n3mVNoXbCl1v1C8m3OJ5fDRcATCOW6ulprB3Kqzn07C/zlAHxIi9OoM/Q/2wAj96Sf3VODu6EQOz62+8YoNcBl9ox8DiUae6VTNKIN4BEWaFA8/t74vr4YHWI0kVazKyd1+F1i/3s+zzHcJ40DdiQFtZFHUa3pQASF5wIymKvK8AlqoIeUrfC6V1sSofeDli+5MspxWFmqrf/JHSWNYfNsEBxLnL6LO6OEV9cb21erO6HrrqLs44SmQk6bOiIi5vDOzEFM5L3SkJD+DHEPgE0D4Ostt86471zzDQin1qQc2QxVeZq9aXjePU95EOU/XTR/fVl77GkP8fDJmLI6d1o3q8gCKgXkxfbKoDQ+E2OZuPhVu/Icam6OfFzFsztESxc8SQo8UHYRwYbc9FPt7O0XuquTJaUdcxKlLB6uG8kFXZ8jGimUvPdnGfdK1jZBTen6ENzEKFIjyyOtG/vbV4aiNj+DwR3Y7arokbnwlZmhXmPzHuuw9jwyl10+lAyBgI3YS65uXTLBpcjunP3vulL1XM2cDPdNeuWO86AtYUhYxvu9Mw3iALgWU760lVdGep23VUK7ASahMlMw50a9udAKcXcJ3MNFqxOc2ku3jxvNJbRdNyEn1hen/E4ESqyWzPyU/zt9ozfio7JbipOnnBPpitYBqWI8Yg3mGSXfXIe+w+DBLDIun3uhqL4V/AMUtjy6TUA=,iv:qdr6VIP949of3kdRzU/+KkP4wdxwsEl8VQmaIpJVUc0=,tag:petIStpCZ5WDVVy+9Xvzlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRG9KeThEVjQ2L3Rjblcy
            TnJCWWJEZDB1cVFHcjNUOHdRNW1qaFRnUWs4ClU2enU1U1BzeG9RT3I5ZDM4V0FU
            ODBmVEszVk5FS3d6L3g4d3RTL2x4U1EKLS0tIHF4bGp0bW5BQVl0aUdsb095Wis1
            alh5YkJQekI4a1l3bW9icWk2VC95Sm8KAwh2n+2LOBAu2G+GACZ/AMlMuw0C6VSm
            mtKvC+0GVbMnVS1VqRyYavl8L0DHj2mM5KUJopqXhJ6MQCY/aXA4tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwdptp2f9jqzugvkvapf4ssqdt3xm0mn8tq9f9xrqdf8kazsn3js6ftmg6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQjE2VTM4MmhUQXlaNnN6
            WVMrQUg5b3VTbUxtTWVBY3hnWFVCSlhOam4wCmtYeCtvZlpkdEQzOUhZb2swY0pN
            UXdTTE1jVTdUOEt3YW9aVis5djZOYkEKLS0tIGJrbHh3ZC9JdkZwdEx3c3VVeVVO
            ZlRYTGFOMWZ5Ni9sMVR3SjdOKytMQUkKzzoqKD4HyjclWC6ZXxuZNu0cg+a5oeDO
            wjrF4YREZLgqiJhbTj7rGnR1rVZgMEkxtz6+vFaG0G4opVUrxAIOQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwmwwqm7tm7msj9jl5yj6gxrjnkpc8qykgpux9u7x6nhg8llus4qk2e7ds
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV09XUHp1dmRFUnRmUkFm
            Z2lyWElyVnVkVlVXcnZJeVVET3lQWlM4QzNZCjV1VXJkZitWVDBtczJ5THlQZTNz
            MHUzbUhOd3F6NDlPalJJOTgrMGhVbVEKLS0tIFgvL0tvaVpueFViU3dtWUp4bzVj
            OGZxT0pCdmdiTWtFdGxxdTdkMzdOVDAKhY97g93/Ln30ucli1+aFffOLnKEv1m+h
            L5WPfYS2EMZaDwWg0ymfb7FQGJumqH5c9ZxgYTGRDFADLMKpEhmJxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e0slax42xt6r7nzwv7kxnkshuewwefu4049zr7wswxzdelajxguqsclvt6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV3UyZXh3RHFPRkx3cEla
            NnRSeUplZ21qVG44aEI5ajRaWlBZRktpTXdrCm5VN0h5dnVjZU1LVGRoZVJ0c1B4
            OW1MQ2N5V09ScXE2Zis2NFRwMEpHQzgKLS0tIE5rNGJHay9oTTBZVWZwWUh2Vkpv
            TjBXcHRKRnZJYjc4eFlkZjFmK1BRbzAKjiXQdM+GvHL746dOfQZX872wrjMrVhg8
            SkiEcjFGsGcs5JQnp6j7a16ml6RVyv9sBTG/IP6OkWDoR9aO42grvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cfcja4l7ar2t4cuscs4xqax22ded73re3wjcvq8ymg39jk8jmgjqnms563
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYk4zTGx5eFVXZHdsVmhk
            emZDOEpUSy9CZ1hsQ2pUOTk1RkRxbUxIc0JvCjZSMXhaKy8rMVYwL0JXQ0dMdWk0
            Q1N1ZFlrRndpdGVYVzNIWVdWTzZPeXMKLS0tICtrQkZ4N292QVA3TXRKbzd2WkJq
            MDh2L0h4ZW9xZ2tVS1pUV2VGSVg2REEKShIBobUD0cRYZUR5qzc6DMudKR/GTi2o
            erv+IqyYv4W4rpvKDsou62gPSRTAD6diUv5y1BULyAyHDGCly0m/UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyrdtt37tgdd7zvrhyhzptjumurdaqymv8e08nvm704u8hd8qcyqp6a3uw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV3BqR0pnSGJsbDVPWEgy
            SGFZSnFzVnMyQWxRVjJpcVJiMkQzU21iRXpzCkthTU1zcUM0NS9nMlY2YW9MR1dr
            VnY0UWg3UEZzYlJWNjFhNG11ZGdtV3MKLS0tIDV6UXNPUDJxcDVQYjl5cUpaUjZ6
            QTdJZS9ZWHg3WXFxOVVHd2tmRytkWjgKymFdw/MzcJO+xQPca1aYvBLkSLCCemtf
            euXpTTSCrc45j+2GLgaFExme8KuOHQolCcJRe5RevnnqwAUBWn/Y1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qlq2enxnf3pgn7ffnp6gc090dymrdfmahh38pu7nxnd9w0dac5ys06rh96
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRmNST3Bhem5rT25nZk5P
            WisybHQ3REc4UldaVHJkZUpFL2RFQ3pKaFFNCkRUVmtnbDlISTA4UzJsWFdrQUR5
            TlNMY0R5T2hPYy95ZTVnS3Y1NU83dTQKLS0tIHZmQkJzdWFZbDF6enZXcWwyKzIy
            YTc4WUdnZjl4cmpJVFVLTlp6ZUJMdVUKwYYf9d0b8T9AFz2/epK0CGWIObAmK8r3
            ll2PNCAEylWSgi58jIdJDQx9DvKyHzJVU3v5DfzznDI1Iip3E+6u0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vs330ap47fuywf4vnl6ngr5xtju06n47n06fv8pc6frpm53e895sl596tj
    lastmodified: "2026-06-16T17:54:23Z"
    mac: ENC[AES256_GCM,data:PpX1B4QZUDDvfDnE4Jm3R1Pp3NgBcJzE6X2YWvf9pXlwa8neNB8ScpphaQyW+p08iKctQ66S5iPRv1p6r3xIYMw5lw0Vq0mdCcEYGVU5b9FApbweDEsfmPWIIyMJUqebuU/BXR5lf9iU1GpcO4Y2mLqJ8PMiqnmdTG2XteQmYhM=,iv:qvTBBma7ZXepgEUtHkUMySVVuuGoASnfT1kcXcDX+7A=,tag:rBhUVZxqfwvXDP7HMyxW+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
