wg:
    mintaka:
        private: ENC[AES256_GCM,data:2Jo2LcfmFY3Eiz1Mb99cdRSPPc3/TixT7AkphLdbgmIWm6yXzpHfVqBTPFQ=,iv:C7bKZF5T8MRuzE9eMuoTDE6F25vmVPoV9qSV3BljjMY=,tag:bYMBnixmUlueZBadK/2JVQ==,type:str]
    bellatrix:
        private: ENC[AES256_GCM,data:Pu3cDh4FkM9/fp6rQxjQMU1TXt3Q8uB9st9pDFhIF8VM28gYmcjS2aL65t4=,iv:aFdRYWUjKwGO3EqkYKQM/Hk9dcYtn+MRYfsq2kNqcT8=,tag:nS+ghIkzsoutS92Vrm5icg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwdptp2f9jqzugvkvapf4ssqdt3xm0mn8tq9f9xrqdf8kazsn3js6ftmg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTXNDSmsxV0NsWHBvSXJ6
            Mm8yWHNWNzJpN1oxZE50NWdyakk4Q0JLbmxFCkh4MHBhS0Zuak1Ndmc1NlIwT2h5
            ZGVCM2R2dGlWZGpyRUN2YTlsYW5Ua2sKLS0tIGtNUzFaQVEyWFhSOEtrMkhRWWFn
            VEZEN3pPYlRPMUs5aTJwQmxsZjF3QkUKUU4yspnnScgIwP+hdBjs8fAKlWXTVOja
            er85zyOag3HUE3DdRJ9fvRlxlAVgpDg8mZqdSzZ5/qdj2NBoh++qag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wwmwwqm7tm7msj9jl5yj6gxrjnkpc8qykgpux9u7x6nhg8llus4qk2e7ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcDBVK1l5RzBqMFczUGZv
            SVpWVk1XSmVEMEg0WldPdEZPeHBCU1FabkZ3Ck0rbDhXNGNneTFMVHpxZVdrV0VZ
            TlJWdCtFRDVuUkpNU0RmQlREeHh6TE0KLS0tIFgramI1eTFpUjVJdlQrKy85cHJi
            NHFRTG4vS01jL3dscmtwdGJkbHhDcVEKUXZRqAzEk2E+B2E9yH9swI2hmjvSXQm7
            0uqXGHJEt+nj9Hhy4kUfNfurOnQ/JgVbyvCXmopvoNLwhOGCJn2VlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e0slax42xt6r7nzwv7kxnkshuewwefu4049zr7wswxzdelajxguqsclvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NlZwc2VaMnovNStNTExB
            UGIxTE52bmsxZzMxTktRc1krT0J6M3Q1UlhRCjBYVnJ6d1FLWDI4M1QyVWRXUG5i
            R1gyNE4wcVV4SFRzMzhHSEZZRFp0cEUKLS0tIGFHcVR4ajdrZWxiUWwrMTNsNlVl
            MXczS1hZcUNPUUQ3L1BmajhRVGM0UEEKqyhKLg6+HOslpjgmHDV8U9hdVukVdo05
            Ax57ToE3krw0TwEyn8WFqZMhkw/mrLLiNmXnA7Ft1FjGAjJ2Z+38Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T15:16:50Z"
    mac: ENC[AES256_GCM,data:yA9ucqqX3kFZiN+qQSRgBodai+6bTOjBJFf+xwE/cTuoqY6fdpYpXEakEnCOckix6+Kr6iFbh7Fb+trNEGva3KfJo/xA5ZQct8otvni6JtmuQfsc4pwfFkPy7hkf5Yor9P8u5bG+B0WgKfw0NEteXYadzRaIie2thYbs1F2cWKw=,iv:GeMANo2N4GxJ4ks6pAQLB2kZ1lCzCoLVnOxbKfU5Cq8=,tag:R41pFFUrSGm7lc3rYK7eQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
